# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  DIST: bin
  OUT: trackposter

  # Leaving it empty
  CI:

tasks:
  build:
    desc: Run tests and builds project
    env:
      CGO_ENABLED: 0

    sources:
      - "**/*.go"
    method: checksum
    cmds:
      # Test all package
      - go test -v ./...

      # Build
      - go build -o {{.DIST}}/{{.OUT}}{{if eq .GOOS "windows"}}.exe{{end}} -ldflags="-s -w" ./cmd/trackposter
    silent: false

  run-tests:
    desc: Run tests
    env:
      # Using cgo for -race flag
      CGO_ENABLED: 1
      CI: "{{.CI}}"

    sources:
      - "**/*.go"
    method: checksum
    cmds:
      - go test -v ./...
      - go test -race ./...
    silent: false

  run-windows:
    desc: Runs Trackposter from source
    deps:
      - task: build
        vars: { GOOS: windows, GOARCH: amd64 }

    cmds:
      - ./bin/{{.OUT}}.exe
